### ISSUE TITLE
redirects for upcoming deployment to prod

### ISSUE THREAD

**Issue by blaflamme** [Pylons/pylonsproject.org#28]
Here's a list of current URLs that need a new mapping:

| Current | New |
|---------|------|
| /about | /about-pylons.html |
| /about/pylons | /about-pylons.html |
| /about/history | /history.html |
| /about/license | /license.html |
| /projects | /projects.html |
| /projects/pyramid/about | https://trypyramid.com |
| /projects/pyramid/faq | https://trypyramid.com |
| /projects/pyramid/download | https://trypyramid.com |
| /projects/pylons-framework/about | about-pylons-framework.html |
| /projects/pylons-framework/download | about-pylons-framework.html |
| /community | /community-participate.html |
| /community/how-to-participate | /community-participate.html |
| /community/how-to-contribute | /community-contribute.html |
| /community/code-of-conduct | /code-of-conduct.html |
| /community/get-support | /support.html |
| /tools | / |
| /tools/pastebins | / |

**Comment by stevepiercy** [comment]
Suggested changes.

# Rename
/about-pylons.html -> /about-pylons-project.html to be consistent with page title and purpose, and to disambiguate between the project and framework.

# Redirect
/about/history -> /about-pylons-framework.html

# Merge content
Move content from /history.html into /about-pylons-framework.html and delete /history.html. The label on the old site (About/Pylons Project) is misleading because its content is only about the history of the Pylons Framework before the Pylons Project existed.

**Comment by blaflamme** [comment]
@stevepiercy +1 for this, will do next.

**Comment by blaflamme** [comment]
Done
