### ISSUE TITLE
Host static websites on GitHub pages

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#58]
Discussion started in https://github.com/Pylons/pylonsproject.org/issues/57#issuecomment-309146071

At this moment, none of our sites are dynamic. That includes:

* trypyramid.com
* pylonsproject.org
* static.pylonsproject.org
* webob.org

We have plans to make trypyramid.com dynamic to handle submission and curation of add-ons and "Powered by Pyramid" listings, and possibly other features like those conceived in [NotAliens](https://github.com/sontek/notaliens.com).

**Comment by ikolar** [comment]
Would something like [this](https://ikolar.github.io/pylonsproject.org/index.html) work?

I added a "docs" command into packages.json that runs the dist operation then copies over the files into docs/. I then configured github pages to be hosted from there. I also had to make the urls in nav.ejs relative for now on.

To deploy, after each change, you'd have to "npr run docs" and the commit the changed docs dir to the upstream master. Github pages should refresh in a couple of minutes.

If this sounds ok, please let me know what else I need to fix and I'll prepare a pull request.

**Comment by stevepiercy** [comment]
Since the time I created this issue, we've implemented HTTPS for all our domains as well as nginx proxy per #56. Would hosting on GitHub pages support this? If not, then I should close this issue as a "won't fix".

How often and how long is there a delay in refreshing GitHub pages? It's not a deal-breaker, but something to be aware of in case we're wondering, "Why didn't my changes take effect?"

Thanks for exploring this issue.

**Comment by ikolar** [comment]
Https is a bit tricky. The github.io subdomain obviuosly supports https, but if you want to secure your own domain you can't do that on github directly. You need to transfer the domain to cloudflare and set up (free) ssl there. See (this issue)[https://github.com/isaacs/github/issues/156] foe details.

The rebuild times are ok but not perfect. The dics say they rebuild on commit, with a soft limit of 10 rebuild per hour. However, i did have to wait a few minutes to see the site, and it took an additional 30 mins or so for / to automatically redirect to index.html. but i'm guessing that's only for the first deploy.

Your call. If you're happy with linode i wouldn't recomnend switching.

**Comment by stevepiercy** [comment]
Thanks for the info. We absolutely want to use custom domains, and the [issue you cited](https://github.com/isaacs/github/issues/156) is not yet resolved. That's a deal-breaker until it gets resolved. I'll leave this issue open.

**Comment by ikolar** [comment]
Ok. 

Offtopic: I've got some spare time in the comming weeks, are there any other simple* pylons/ pyramid issues that need looking at?

**Comment by stevepiercy** [comment]
Issues marked [sprintable](https://github.com/Pylons/pyramid/labels/sprintable) are a good bet.

**Comment by bertjwregeer** [comment]
@stevepiercy We could set up a reverse proxy like we did with RTD. Host the site on GitHub.io, but reverse proxy so we get SSL...

**Comment by stevepiercy** [comment]
@bertjwregeer RTD uses a [custom header, `X-RTD-SLUG`](https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl). Does GitHub.io support something similar, or would it "just work" without a custom header?

**Comment by bertjwregeer** [comment]
Here's an example page that shows how to do it: https://pascal.io/github-pages-https/

We could make some tweaks to it, and use `proxy_pass` to the `https` address, but that should be all that is required.

**Comment by stevepiercy** [comment]
OK, let's give it a shot with webob.org as the guinea pig. It's just a single `.html` and `.css` file. I'll work on this tonight.

If successful, then we can apply it to pylonsproject.org and trypyramid.com with @ikolar's suggestion.

**Comment by mmerickel** [comment]
I expect we're talking about doing this for `pylonsproject.org`, `trypyramid.com` and `webob.org`.

GH Pages offers 3 ways to do this:

1. Create a gh-pages branch which they will serve statically.
2. Serve directly from master (basically assuming the repo only contains the built product).
3. Serve the `/docs` folder in master.

Option 2 is definitely out because we'd need to find another place to contain the source so it's basically option 1 or option 3. I thought about it for a bit and think the gh-pages approach is best for our situation. This gives us a bit more explicit control on what's being served and the repo structure just doesn't make as much sense otherwise.

It's quite simple - the steps for our projects would be basically:

1. Create a gh-pages branch which will serve the site and push the rendered html and other assets to that branch.
2. Configure the repo under Settings to set Pages to use the gh-pages branch.
3. Test that you can visit repo.github.io and view the site.
4. Configure nginx to proxy the canonical site url to repo.github.io.

To perform updates in the future:

1. Contribute changes to the repo.
2. Build the site and commit / push it to the gh-pages branch.

We could look into setting up something else to build staging versions of the site via travis per-pull-request but it would not invalidate this setup so I don't see it as a bad way to go.

**Comment by bertjwregeer** [comment]
At Crunch we use Github's pages along with Hugo and travis to push changes back to GH after building. It works pretty well.

**Comment by bertjwregeer** [comment]
This is now completed for pylonsproject.org and try pyramid.com, webob.org is still a special snowflake for right now.

PPO and TPC are both proxied from our Linode instance to Github pages, this way we keep IPv6 support (Github Pages doesn't support it).
